name: createTimeZones

on:
  schedule:
    - cron: '0 0 1 * *'
    - cron: '0 0 15 * *'

jobs:
  call-api:
    runs-on: ubuntu-latest
    
    steps:
      - name: Make cURL request
        run: |
          curl -X GET https://timeconverter-d3a3.onrender.com/timeframe/stored_urls
